### Site Settings ###
title       : otto
description : Youssef in binary.
baseurl     : "/otto"
repository  : YoussefRaafatNasry/otto
logo        : master/app/src/main/res/mipmap/ic_launcher.png
meta-img    : gh-pages/meta.png