### Site Settings ###
title       : otto
description : Youssef in binary.
baseurl     : "/otto"
repository  : YoussefRaafatNasry/otto
logo        : bc57e27d8f39644b6153bf2171be71ab6fed711c/app/src/main/res/mipmap/ic_launcher.png
meta-img    : gh-pages/meta.png
